---
- name: Generating Host file
  hosts: all
  tasks:
          - name: Creating Host file from inventory
            template:
                    src: hosts.j2
                    dest: /etc/hosts
